
# Set here configurations for the database connection
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/tenant_db?createDatabaseIfNotExist=true


  # Show or not log for each sql query
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  application:
    name: Tenant Management System

    # load default data into table
  sql:
    init:
      mode: always

server:
  port: 8888

